// <auto-generated />
namespace proiect_useri.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MissingXXX : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MissingXXX));
        
        string IMigrationMetadata.Id
        {
            get { return "202101021759491_MissingXXX"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
